version: "3.7"

services:
  mysqldb:
   container_name: mysqldb1
   image: mysql:5.6
   restart: unless-stopped
   ports:
    - 3307:3306
   environment:
    MYSQL_DATABASE: achatdb
    MYSQL_ROOT_PASSWORD: root
   volumes:
     - /home/mysql/data:/var/lib/mysql --user 1000

  spring_app:
   image: flawnrayen/achatapp_testt
   restart: unless-stopped
   container_name: achatapp_test
   ports:
    - 8082:8082
   depends_on:
    - mysqldb
