version: "3.7"

services:
  mysqldb:
   container_name: mysqldb1
   image: mysql:5.6
   restart: unless-stopped
   ports:
    - 3307:3306
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: achatdb
    MYSQL_ROOT: root
    MYSQL_PASSWORD: root
   volumes:
     - /home/mysql/data:/var/lib/mysql --user 1000

  spring_app:
   image: flawnrayen/achatapp_testt
   container_name: achatapp_test
   ports:
    - 8089:8089
   environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC  
   restart: on-failure
   depends_on:
    - mysqldb
